version: '2'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    healthcheck:
      test: nc -z localhost 2181 || exit 1
      interval: 5s
      timeout: 5s
      retries: 60
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
    networks:
      - kafka-net
    ports:
      - 22181:2181
    volumes:
      - /Users/rmx/docker-compose/kafka_cassandra/volume/zookeeper/data:/var/lib/zookeeper/data
      - /Users/rmx/docker-compose/kafka_cassandra/volume/zookeeper/log:/var/lib/zookeeper/log
  
  kafka-server1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-server1
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 5s
      timeout: 5s
      retries: 60
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server1:9092
    volumes:
      - /Users/rmx/docker-compose/kafka_cassandra/volume/kafka-server1/data:/var/lib/kafka/data
  
  kafka-server2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-server2
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 5s
      timeout: 5s
      retries: 60
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    ports:
      - 29093:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server2:9092
    volumes:
      - /Users/rmx/docker-compose/kafka_cassandra/volume/kafka-server2/data:/var/lib/kafka/data
  
  kafka-server3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-server3
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 5s
      timeout: 5s
      retries: 60
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    ports:
      - 29094:9092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server3:9092
    volumes:
      - /Users/rmx/docker-compose/kafka_cassandra/volume/kafka-server3/data:/var/lib/kafka/data

  kafka-sr1:
    image: confluentinc/cp-schema-registry:latest
    container_name: kafka-sr1
    healthcheck:
      test: nc -z kafka-sr1 8081 || exit 1
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - kafka-net
    ports:
      - 28081:8081
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka-server1:9092,kafka-server2:9092,kafka-server3:9092
      - SCHEMA_REGISTRY_HOST_NAME=kafka-sr1
      - SCHEMA_REGISTRY_LISTENERS=http://kafka-sr1:8081
    depends_on:
      - zookeeper

  kafka-connect1:
    image: 'confluentinc/cp-kafka-connect:latest'
    container_name: kafka-connect1
    healthcheck:
      test: nc -z localhost 8083 || exit 1
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - kafka-net    
    ports:
      - 28083:8083
    volumes:
      - /Users/rmx/docker-compose/kafka/volume/kafka-connect/vol-kafka-connect-jar:/etc/kafka-connect/jars
      - /Users/rmx/docker-compose/kafka/volume/kafka-connect/vol-kafka-connect-conf:/etc/kafka-connect/connectors
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-server1:9092,kafka-server2:9092,kafka-server3:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: cassandraConnect
      CONNECT_CONFIG_STORAGE_TOPIC: cassandraconnect-config
      CONNECT_OFFSET_STORAGE_TOPIC: cassandraconnect-offset
      CONNECT_STATUS_STORAGE_TOPIC: cassandraconnect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: false
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: false
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_PLUGIN_PATH: /etc/kafka-connect/jars
    depends_on:
      - zookeeper
      - kafka-server1
      - kafka-server2
      - kafka-server3

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - kafka-net
    depends_on:
      - kafka-server1
      - kafka-server2
      - kafka-server3
    ports:
      - 28080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - /Users/rmx/docker-compose/kafka_cassandra/volume/kafka-ui/dynamic_config.yaml:/etc/kafkaui/dynamic_config.yaml

  cassandra-server1:
    image: cassandra:latest
    container_name: cassandra-server1
    mem_limit: 2g
    healthcheck:
      test: ["CMD-SHELL", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - kafka-net
    ports:
      - 29042:9042
    environment:
      CASSANDRA_SEEDS: cassandra-server1
      CASSANDRA_CLUSTER_NAME: TestEnv
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    volumes:
      - /Users/rmx/docker-compose/kafka_cassandra/volume/cassandra:/var/lib/cassandra
      - /Users/rmx/docker-compose/kafka_cassandra/volume/cassandra_etc/cassandra.yaml:/etc/cassandra/cassandra.yaml
